name: EFFJAYS
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09076262
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#87BCB5'
    - '#160D17'
    - '#7F654B'
    - '#43B4A3'
    - '#FB884B'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
