collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5702103
  brandStrength: 0.8372717
  lightness: 0.7472251
  brandColors:
    - '#280142'
    - '#42FF15'
    - '#FAFB21'
    - '#4201E9'
    - '#F30216'
  rhythmicContrast: 0.7016522
typography_spectrum: 0.09076262
layout_spectrum: 0.6954887
name: EFFJAYS
